services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env  # OpenAI APIキーなどをコンテナに渡す
    container_name: incident-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend  # バックエンドが先に起動するように設定
    container_name: incident-frontend